server:
  port: 8080  # 원하는 포트로 변경할 수 있음 (예: 80, 443 등)

spring:
  datasource:
    url: jdbc:mysql://${ secrets.DB_ENDPOINT }:3306/memo-db
    username: ${ secrets.DB_USERNAME }
    password: ${ secrets.DB_PASSWORD }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate, none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  logging:
    level:
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: ERROR
